export const products = [
    {
        name: "Queso",
        price: 2.5,
        id: 528467,
        descrip:
          "Es un alimento elaborado a partir de la leche cuajada de vaca, cabra, oveja u otros mamíferos.",
         image:require("../../assets/img/queso-fresco.png"),
      },
      {
        name: "Galletas",
        price: 1.2,
        id: 789424,
        descrip:
          "Las galletas o galletitas comerciales pueden ser: dulces o saladas. Las dulces a su vez se dividen en secas, rellenas u obleas. ",
          image:require("../../assets/img/galletas.png"),
      },
      {
        name: "Yogurh",
        price: 5.9,
        id: 627483,
        descrip: " Producto de leche coagulada obtenida por la fermentación láctica. ",
        image:require("../../assets/img/yogurt.png"),
      },
      {
        name: "Pasta Dental",
        price: 1,
        id: 172564,
        descrip: "Es una sustancia química que, como hemos dicho, es una de las partes indispensables de la higiene dental diaria.",
        image:require("../../assets/img/pasta-dental.png"),
      },
      {
        name: "Reloj",
        price: 23,
        id: 222322,
        descrip: "Instrumento capaz de medir, mantener e indicar el tiempo en unidades convencionales.",
        image:require("../../assets/img/reloj.png"),
      },
      {
        name: "Luces Led",
        price: 13.99,
        id: 664782,
        descrip: "Es un elemento capaz de recibir una corriente eléctrica moderada y emitir una radiación electromagnética transformada en luz.",
        image:require("../../assets/img/luces-led.png"),
      },
      {
        name: "Carnes",
        price: 3.5,
        id: 906453,
        descrip: " Parte muscular de todo animal comestible (vaca, cerdo, aves, pescado, cordero, animales de caza.)",
        image:require("../../assets/img/carne.png"),
      },
      {
        name: "Detergente",
        price: 2.5,
        id: 900066,
        descrip: "Producto de limpieza que suele contener surfactantes para disolver los aceites y grasas en agua y eliminarlos con más facilidad.",
        image:require("../../assets/img/detergente.png"),
      },
      {
        name: "Frutas",
        price: 3.2,
        id: 345673,
        descrip: "Es el producto alimenticio comestible que se obtiene de plantas o árboles. ",
        image:require("../../assets/img/frutas.png"),
      },
      {
        name: "Tarjeta Grafica",
        price: 200,
        id: 111653,
        descrip: "Es una tarjeta de expansión de la tarjeta madre o motherboard del computador que se encarga de procesar los datos.",
        image:require("../../assets/img/targeta-grafica.png"),
      },
      {
        name: "Juguetes",
        price: 45,
        id: 888640,
        descrip: "Es un objeto diseñado para entretener y divertir a las personas, especialmente a los niños.",
        image:require("../../assets/img/juguetes.png"),
      },
      {
        name: "Celular",
        price: 400,
        id: 667845,
        descrip: "Es un dispositivo de telecomunicación independiente.",
        image:require("../../assets/img/celular.png"),
      },
      {
        name: "Croquetas",
        price: 6.2,
        id: 558676,
        descrip: "Una galleta pequeña pero llena de proteínas, minerales, vitaminas, grasas y carbohidratos. ",
        image:require("../../assets/img/croquetas.png"),
      },
      {
        name: "Consolas",
        price: 120,
        id: 654831,
        descrip: "Es un sistema electrónico de entretenimiento para el hogar que ejecuta juegos electrónicos.",
        image:require("../../assets/img/consola.png"),
      },
      {
        name: "Libros",
        price: 17.2,
        id: 829350,
        descrip: "Es un conjunto de hojas de papel o algún material.",
        image:require("../../assets/img/libros.png"),
      },
      {
        name: "Frascos",
        price: 11.3,
        id: 586732,
        descrip: "Vaso de cuello recogido, hecho de vidrio u otra materia, que sirve para contener líquidos.",
        image:require("../../assets/img/frasco.png"),
      },
      {
        name: "Electrodomesticos",
        price: 16.99,
        id: 908343,
        descrip: "Son los aparatos electrónicos que realizan distintas funciones en el hogar.",
        image:require("../../assets/img/electrodomestico.png"),
      },
      {
        name: "PlayStacion",
        price: 500,
        id: 856723,
        descrip: "Es una videoconsola portátil de la multinacional de origen japonés, Sony Computer Entertainment.",
        image:require("../../assets/img/play-station.png"),
      },
      {
        name: "Parlates",
        price: 59.69,
        id: 999070,
        descrip: "Dispositivo destinado a la conversión de ondas eléctricas en energía mecánica y de mecánica en acústica.",
        image:require("../../assets/img/parlantes.png"),
      },
      {
        name: "Perfumes",
        price: 15.9,
        id: 901291,
        descrip: " Es una mezcla de materias primas odoríferas con una estructura determinada. ",
        image:require("../../assets/img/perfumes.png"),
      },
];